# config.yaml
paths:
  images_dir: "./data/Images_2"
  labels_dir: "./data/Labels_2"
  memmap_dir: "./memmap_output"
  save_model_path: "best_prithvi_11bands.pth"

dataset:
  img_size: [1024, 1024]
  crop_size: 512
  num_bands: 11
  num_classes: 19
  val_size: 0.5
  num_cores: 4

training:
  epochs: 25
  patience: 10
  learning_rate: 0.00005  # 5e-5
  batch_size: 8
  weight_decay: 0.05